config/routes.rb
Simplestore::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  root to: 'store#index', as: 'store'

  get "sessions/new"

  get 'signup', to: 'users#new', as: 'signup'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :products do
    get :who_bought, :on => :member
  end

  get "home/index"

  root :to => 'store#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simplestore</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
    <div id="banner">
        <%= @page_title || "Simple Store" %>
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
    </div>
    <div id="columns">
        <div id="side">
          <% if !@cart.blank? %>
            <div id="cart">
                <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
                <%= render @cart %>
              <% end %>
            </div>
          <% end %>
          
            <ul>
                <li><%= link_to "Catalog (home)", store_path %></li>
                <li><%= link_to "Product Admin", products_path %></li>
                <li><%= link_to "Order Admin", orders_path %></li>
            </ul>
        </div>
        <div id="main">
            <%= yield %>
        </div>
</body>
</html>